### ISSUE TITLE
loadtable / JuliaDB

### ISSUE THREAD

**Issue by kafisatz** [davidanthoff/csv-comparison#4]
Would it be meaningful to add `loadtable` from JuliaDB? 
Or is `loadtable` using one of the existing functions of your list. 
I quickly glanced at your code and it seems it would be straightforward to add this (or am I missing something)?

**Comment by davidanthoff** [comment]
I believe `loadtable` should be identical to `TextParse.jl`.

**Comment by kafisatz** [comment]
I think you are right. I did not realize this.
